# TODO (2a): Write a Dockerfile to run the app on Tomcat as ROOT.war
# Hint: FROM tomcat:9.0.91-jdk11-temurin
#       remove default ROOT, COPY simpleWebApp.war to webapps/ROOT.war
# EXPOSE 8080 and run catalina.sh
